source 'https://github.com/phw2016/OneDSpecs.git'
use_frameworks!

platform :ios, '9.0'

target 'OneDKit_Example' do
  pod 'OneDKit', :path => '../'

  target 'OneDKit_Tests' do
    inherit! :search_paths

    
  end
end
